on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.0'

      - name: Setup GO environment
        run: |
          go mod download
          go get -t .


      - name: Unit tests
        run: |
          sudo go test ./... -coverprofile coverage.txt
          sudo go tool cover -func coverage.txt
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov
